name: Release Reminder

on:
  schedule:
    # Runs on the 1st of every month at 9:00 AM UTC
    - cron: '0 9 1 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  check-last-release:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get latest release
        id: get-latest-release
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const latestRelease = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const lastReleaseDate = new Date(latestRelease.data.published_at);
              const threeMonthsAgo = new Date();
              threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
              
              if (lastReleaseDate < threeMonthsAgo) {
                const existingIssues = await github.rest.issues.listForRepo({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'open',
                  labels: ['release-reminder']
                });
                
                if (existingIssues.data.length === 0) {
                  await github.rest.issues.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: '📦 Release Reminder: No releases in 3 months',
                    body: `The last release was on ${lastReleaseDate.toLocaleDateString()}.\n\nConsider creating a new release if there have been significant changes since then.`,
                    labels: ['release-reminder']
                  });
                }
              }
            } catch (error) {
              if (error.status === 404) {
                // No releases yet
                core.setFailed('No releases found for this repository');
              } else {
                throw error;
              }
            }
